[workspace]
channels = ["conda-forge", "Auto-Mech"]
platforms = ["linux-64"]
preview = ["pixi-build"]                                  

[dependencies] 
mess = { path = "." }

[package] 
name = "mess"
version = "2.10.18"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.*" }

[package.build.config]
extra-args = [
    "-DCMAKE_BUILD_TYPE=Release",
]

[package.build-dependencies]
fortran-compiler = "*"

[package.host-dependencies]
openblas = "*"
slatec = "*"
gsl = "*"
openmp = "*"

[package.run-dependencies]
slatec = "*"
