[workspace]
channels = ["conda-forge", "Auto-Mech"]
platforms = ["linux-64"]
preview = ["pixi-build"]                                  

[dependencies] 
mess = { path = "." }

[package] 
name = "mess"
version = "2.10.24"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.*" }

[package.build.config]
extra-args = [
    "-DCMAKE_BUILD_TYPE=Debug",
    "-DMKL_INTERFACE=ilp64",
    "-DMKL_THREADING=intel_thread",
    "-DMKL_LINK=dynamic",
    "-DMKL_DIR=$PREFIX"
]

[package.build-dependencies]
fortran-compiler = "*"

[package.host-dependencies]
mkl-include = "*"
mkl-devel = "*"
mkl = "*"
slatec = "*"
gsl = "*"
gdb = "*"

[package.run-dependencies]
slatec = "*"
gdb = "*"
