[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "win-64"]
preview = ["pixi-build"]                                  

[dependencies] 
mess = { path = "." }

[package] 
name = "mess"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.3.*" }
