package:
  name: mess 
  version: 2.10.0

source:
  path: .
  use_gitignore: true 

build:
  number: 0
  script: | 
    cmake $CMAKE_ARGS \
      -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=$PREFIX \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DBUILD_SHARED_LIBS=ON \
      -B $SRC_DIR/../build \
      -S .

    cmake --build $SRC_DIR/../build --target install

requirements:
  build: 
    - ${{ compiler('fortran') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - ninja

  host: 
    - blas
    - openblas
    - gsl
    - qd