[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]
preview = ["pixi-build"]

[dependencies]
mess-static = { path = "." }

[package]
name = "mess-static"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "0.3.*" }

[feature.dev.dependencies]
rattler-build = "*"

[feature.dev.tasks]
upload = "rattler-build upload anaconda -o Auto-Mech *.conda || true"

[environments]
dev = ["dev"]
