name: Build and Upload MESS-Static

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.9
        with:
          manifest-path: static/pixi.toml

      # Build
      - name: Build
        run: pixi build
        working-directory: static/

      # Upload
      - name: Upload
        if: ${{ github.ref == 'refs/heads/master' && github.repository_owner == 'Auto-Mech'}}
        run: pixi run upload || true
        env:
          ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_KEY }}